[tool.poetry]
name = "sound-caster-client"
version = "0.0.1"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
typer = "^0.12.5"
PyAudio = "^0.2.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
