[tool.poetry]
name = "sound-caster-server"
version = "0.0.1"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
ipywidgets = "^8.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
